server:
  port: 8000

spring:
  application:
    name: configserver
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Yannick-Bribaud/configserver-files.git"
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true
        #native:
          #search-locations: "classpath:/config/"
         #search-locations: "file:///C://config"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  #Prometheus config
  metrics:
    tags:
      application: ${spring.application.name}


encrypt:
  key: "394659EAAF4B9EA252B5F1DBEB523A8B"

logging:
  level:
    com:
      upsilon:
        configserver: DEBUG
  #OpenTelemetry config
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
    console: "%green(%d{yyyy-MM-dd' 'HH:mm:ss.SSSXXX}) %blue(%-5level) %red([%thread]) %yellow(%logger{20}) - %msg%n"

